
FROM node:alpine AS REACT_BUILD

ENV NODE_ENV production

WORKDIR /app

COPY ./package.json .
RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

ENV NODE_ENV production


COPY --from=REACT_BUILD /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]